name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Check if S3 bucket exists
        id: check_bucket
        run: |
          if aws s3 ls "s3://elasticbeanstalk-us-east-2-396913728093" 2>&1 | grep -q 'NoSuchBucket'; then
            echo "Bucket does not exist."
            echo "bucket_exists=false" >> $GITHUB_ENV
          else
            echo "Bucket exists."
            echo "bucket_exists=true" >> $GITHUB_ENV
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
      - name: Create S3 bucket if not exists
        if: env.bucket_exists == 'false'
        run: aws s3 mb s3://elasticbeanstalk-us-east-2-396913728093
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "Tasks-server"
          environment_name: "Tasks-server-env"
          region: us-east-2
          version_label: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_id }}-${{ github.event.head_commit.timestamp }}
          deployment_package: target/todo-server-0.0.1-SNAPSHOT.jar
          wait_for_deployment: true
          use_existing_version_if_available: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2